# ----------
# General
# See https://wiki.hyprland.org/Configuring/Variables/ for more
# ----------

general {
    col.active_border = rgb(bd93f9) rgb(44475a) 90deg
    col.inactive_border = rgba(282a36dd)
    col.nogroup_border = rgba(282a36dd)
    col.nogroup_border_active = rgb(bd93f9) rgb(44475a) 90deg
    no_border_on_floating = false
    border_size = 3

    layout = dwindle
}
