#██╗  ██╗██╗████████╗████████╗██╗   ██╗
#██║ ██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#█████╔╝ ██║   ██║      ██║    ╚████╔╝ 
#██╔═██╗ ██║   ██║      ██║     ╚██╔╝  
#██║  ██╗██║   ██║      ██║      ██║   
#╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝ 



font_family      Hack Nerd Font
font_weigth      SemiBold
bold_font        auto
italic_font      auto 
bold_italic_font auto

font_size 11.2
window_padding_width 14
include theme.conf
confirm_os_window_close 0